apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - path: success-patch.yaml
    target:
      group: cascade.cascade.net
      version: v1alpha1
      kind: CascadeAutoOperator
      name: cascadeautooperator.*
      labelSelector: "app=cascade"
  - path: success-service-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      labelSelector: "app=cascade"
