{{- range .Values.roles }}
---
{{- if eq .role_binding true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "cascadeAutoOperator.labels" $ | nindent 4 }}
  name: {{ include "cascadeAutoOperator.name" $ }}-{{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cascadeAutoOperator.name" $ }}-{{ .name }}
subjects:
- kind: {{ .kind }}
  name: {{ include "cascadeAutoOperator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}

{{- range .Values.scenarioController.serviceAccount.roles }}
---
{{- if eq .role_binding true }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "cascadeAutoOperator.labels" $ | nindent 4 }}
  name: {{ include "cascadeAutoOperator.name" $ }}-{{ .name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cascadeAutoOperator.name" $ }}-{{ .name }}
subjects:
- kind: {{ .kind }}
  name: {{ $.Values.scenarioController.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}