# Service account for operator deployment
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cascadeAutoOperator.serviceAccountName" . }}
  labels:
    {{- include "cascadeAutoOperator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.scenarioController.serviceAccount.create }}
---
# Service account for scenario controller deployment
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scenarioController.serviceAccount.name }}
  labels:
    {{- include "cascadeAutoOperator.labels" . | nindent 4 }}
  {{- with .Values.scenarioController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}