apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
  - path: fail-last-patch.yaml
    target:
      group: cascade.cascade.net
      version: v1alpha1
      kind: CascadeAutoOperator
      name: cascadeautooperator.*
      labelSelector: "app=cascade"
