apiVersion: v1
kind: Service
metadata:
  name: {{ include "cascadeAutoOperator.name" . }}-metrics-service
  labels:
    {{- include "cascadeAutoOperator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "cascadeAutoOperator.selectorLabels" . | nindent 4 }}
