apiVersion: cascade.cascade.net/v1alpha1
kind: CascadeAutoOperator
metadata:
  name: cascadeautooperator-ip
  labels:
    app: cascade
spec:
  template:
    spec:
      containers:
      - name: cascadescenario-ip
        image: ghcr.io/randsw/cascadescenariocontroller_v2:0.2.5
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /tmp
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: cascademanualoperator-ip-cm # This field is mutable
      restartPolicy: Always
  scenarioconfig:
    cascademodules:
      - modulename: grayscale
        configuration:  
          foo: bar
          spamm: eggs
          test1: test2
        template:
          spec:
            containers:
              - name: grayscale
                image: ghcr.io/randsw/grayscale:0.1.1
                imagePullPolicy: IfNotPresent
            restartPolicy: OnFailure
        backoffLimit: 0
      - modulename: binarization
        configuration:
          thresh: "128"
          eggs: spamm
          test2: test1
        template:
          spec:
            containers:
              - name: binarization
                image: ghcr.io/randsw/binarization:0.1.1
                imagePullPolicy: IfNotPresent
            restartPolicy: OnFailure
        backoffLimit: 0
      - modulename: diff
        configuration:
          bar: foo
          eggs: spamm
          test2: test1
        template:
          spec:
            containers:
              - name: diff
                image: ghcr.io/randsw/diff:0.1.1
                imagePullPolicy: IfNotPresent
            restartPolicy: OnFailure
        backoffLimit: 0
