apiVersion: v1
kind: Service
metadata:
  name: scenariocontroller
  labels:
    app: cascade
spec:
  selector:
    app: cascadescenario-ip
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP